ARG CADDY_VERSION=latest

FROM fraserdarwent/caddy:${CADDY_VERSION}
ARG KUBERNETES_JSON_SCHEMA_VERSION
ENV KUBERNETES_JSON_SCHEMA_VERSION=${KUBERNETES_JSON_SCHEMA_VERSION}
COPY kubernetes-json-schema/${KUBERNETES_JSON_SCHEMA_VERSION}-standalone /kubernetes-json-schema/${KUBERNETES_JSON_SCHEMA_VERSION}-standalone
COPY Caddyfile /Caddyfile
CMD [ "run" ]