version: 2.1
workflows:
  version: 2
  Build:
    jobs:
      - Build
jobs:
  Build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Make
          command: |
            echo "$(ls -la)"
            make